<?php

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'msg',
  'author' => 'lars.schaps@msg.group',
  'description' => 'Executes sql statements and generates XLS reports.',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'SQLReport',
  'published_date' => '2019-05-08 11:01:36',
  'type' => 'module',
  'version' => 1557313297,
  'remove_tables' => 'prompt',
);

$installdefs = array (
  'id' => 'SQLReport',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'msg_SQLReport',
      'class' => 'msg_SQLReport',
      'path' => 'modules/msg_SQLReport/msg_SQLReport.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
  ),
  'relationships' => 
  array (
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/msg_SQLReport',
      'to' => 'modules/msg_SQLReport',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/de_DE.lang.php',
      'to_module' => 'application',
      'language' => 'de_DE',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
);
